import {
  Wifi,
  Car,
  Wind,
  ShowerHead,
  Shield,
  UtensilsCrossed,
  Bath,
  Droplets,
  Camera,
  Snowflake,
  Tv,
  WashingMachine,
  Dumbbell,
  BookOpen,
  Bike,
  Bus,
  Zap,
  Flame,
  Sofa,
  ParkingCircle,
  Coffee,
  Thermometer,
  Lock,
  Sun,
  Bed,
  Refrigerator,
  Power,
} from "lucide-react";

export const AMENITY_ICONS = {
  "WiFi": Wifi,
  "Parking": ParkingCircle,
  "Balcony": Wind,
  "Attached Bathroom": ShowerHead,
  "Security": Shield,
  "Kitchen": UtensilsCrossed,
  "Bathroom": Bath,
  "Drinking Water": Droplets,
  "CCTV": Camera,
  "AC": Snowflake,
  "Air Conditioning": Snowflake,
  "TV": Tv,
  "Television": Tv,
  "Washing Machine": WashingMachine,
  "Laundry": WashingMachine,
  "Gym": Dumbbell,
  "Study Room": BookOpen,
  "Bike Parking": Bike,
  "Bus Stop Nearby": Bus,
  "Power Backup": Zap,
  "Gas": Flame,
  "Common Area": Sofa,
  "Coffee": Coffee,
  "Geyser": Thermometer,
  "Hot Water": Thermometer,
  "Locker": Lock,
  "Terrace": Sun,
  "Furnished": Bed,
  "Refrigerator": Refrigerator,
  "Fridge": Refrigerator,
  "Electric Backup": Power,
  "Car Parking": Car,
};
